---

- name: Restart nginx
  ansible.builtin.systemd_service:
    state: restarted
    name: nginx

- name: Restart amazon-cloudwatch-agent
  ansible.builtin.systemd_service:
    state: restarted
    name: amazon-cloudwatch-agent
