---

- name: Container app
  community.docker.docker_container:
    name: app
    state: started
    restart: true
    image: rootsh/junto-teste:{{ version }}
    ports:
    - "3000:3000"
    comparisons:
      image: strict