---
- name: Install amazon-cloudwatch-agent
  ansible.builtin.dnf:
    name: amazon-cloudwatch-agent
    state: latest

- name: Service amazon-cloudwatch-agent
  ansible.builtin.systemd_service:
    state: started
    name: amazon-cloudwatch-agent
    enabled: true

- name: Install collectd
  ansible.builtin.dnf:
    name: collectd
    state: latest

- name: Service collectd
  ansible.builtin.systemd_service:
    state: started
    name: collectd
    enabled: true

- name: amazon-cloudwatch-agent conf
  ansible.builtin.copy:
    src: amazon-cloudwatch-agent.json
    dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify:
    - Restart amazon-cloudwatch-agent