---
- name: motd
  ansible.builtin.copy:
    src: motd
    dest: /etc/motd
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: PS1
  ansible.builtin.lineinfile:
    path: /etc/profile.d/ps1.sh
    line: export PS1='\[\e[0;36m\] \T \d \[\e[1;30m\][\[\e[1;34m\]\u@\H\[\e[1;30m\]:\[\e[0;37m\]${SSH_TTY} \[\e[0;32m\]+${SHLVL}\[\e[1;30m\]] \[\e[1;37m\]\w\[\e[0;37m\] \n($SHLVL:\!)\$ '
    create: true

- name: Upgrade all packages
  ansible.builtin.dnf:
    name: '*'
    state: latest
