version: 2.1
orbs:
  node: circleci/node@5
jobs:
  lint-dockerfile:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: Dockerfile Lint
          vars:
            HADOLINT_VERSION: v2.12.0
          command: |
            apk add --no-cache curl
            curl -L https://github.com/hadolint/hadolint/releases/download/{{.HADOLINT_VERSION}}/hadolint-Linux-x86_64 --output /usr/local/bin/hadolint
            chmod +x /usr/local/bin/hadolint
            hadolint Dockerfile
    
  test-node:
    executor: node/default
    working_directory: ~/project/app
    steps:
      - checkout:
          path: ~/project
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run:
          name: Run tests
          command: npm test --passWithNoTests
workflows:
  lint-test:
    jobs:
      - lint-dockerfile
          filters:
            branches:
              ignore:
                - main
      - test-node
          filters:
            branches:
              ignore:
                - main