version: 2.1
orbs:
  node: circleci/node@5
jobs:
  lint-dockerfile:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: Dockerfile Lint
          environment:
            HADOLINT_VERSION: v2.12.0
          command: |
            apk add --no-cache curl
            curl -L https://github.com/hadolint/hadolint/releases/download/$HADOLINT_VERSION/hadolint-Linux-x86_64 --output /usr/local/bin/hadolint
            chmod +x /usr/local/bin/hadolint
            hadolint Dockerfile
    
  test-node:
    executor: node/default
    working_directory: ~/project/app
    steps:
      - checkout:
          path: ~/project
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run:
          name: Run tests
          command: npm test --passWithNoTests

  build-push:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker:
          version: default
      - checkout
      - run:
          name: setup Qemu
          command: |
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - run:
          name: Create builder
          command: |
            export DOCKER_CLI_EXPERIMENTAL=enabled
            docker context create multi-arch-build
            docker buildx create --use multi-arch-build
      - run: |
          export GIT_REPO_NAME=$(basename $(git remote get-url origin) | cut -f1 -d'.')
          export GIT_CURRENT_VERSION=$(git rev-parse --short HEAD)
          echo "export GIT_CURRENT_VERSION=$GIT_CURRENT_VERSION" >> $BASH_ENV
          echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          DOCKER_CLI_EXPERIMENTAL=enabled docker buildx build --push --tag $REPO/$GIT_REPO_NAME:$GIT_CURRENT_VERSION --platform $ARCH .
      - run: |
          cp $BASH_ENV bash.env
      - persist_to_workspace:
          root: .
          paths:
            - bash.env
    environment:
      ARCH: "linux/amd64"
      REPO: rootsh

  deploy:
    working_directory: /tmp/project
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install packages
          command: |
            sudo apt-get update
            sudo apt-get install ansible -y
            ansible-galaxy collection install amazon.aws
            sudo apt-get install python3-boto3 -y
            sudo apt-get install -y gnupg software-properties-common wget -y
            wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
            echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
            sudo apt-get update
            sudo apt-get install terraform -y
            curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
            sudo dpkg -i session-manager-plugin.deb
      - run:
          name: Terraform 
          command: |
            source bash.env
            echo $GIT_CURRENT_VERSION
            cd /tmp/project/terraform
            terraform init
            terraform validate
            TF_VAR_app_version=$GIT_CURRENT_VERSION terraform plan
            TF_VAR_app_version=$GIT_CURRENT_VERSION terraform apply -auto-approve
            export EC2_IP=$(terraform output | awk '{ print $3 }' | sed 's/"//g')
            apk add curl --no-cache
            curl http://$EC2_IP


workflows:
  # lint-test:
  #   jobs:
  #     - lint-dockerfile:
  #         filters:
  #           branches:
  #             ignore:
  #             - main
  #     - test-node:
  #         filters:
  #           branches:
  #             ignore:
  #               - main

  build-deploy:
      jobs:
       - build-push:
          context: docker_hub
          filters:
            branches:
              ignore:
                - main
       - deploy:
          context: aws
          requires:
            - build-push
          filters:
            branches:
              ignore:
                - main