---
- name: app
  hosts: all
  gather_facts: false
  become: true
  become_user: root
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_region: us-east-2
    ansible_aws_ssm_bucket_name: r00tsh.ssm
  roles:
    - role: app